### ISSUE TITLE
No Issue: Thank You for provide amazing theme

### ISSUE THREAD

**Issue by luasenvy** [boluoim/astroberry#2]
i like this theme. thank you again.

Astro is a really good framework, but I rewrote it because I was familiar with nextjs.

If there's anyone like me, I'd appreciate it if you could use it freely.

link: [nextjs-astroberry](https://github.com/luasenvy/nextjs-astroberry)

**Comment by boluoim** [comment]
> i like this theme. thank you again.
> 
> Astro is a really good framework, but I rewrote it because I was familiar with nextjs.
> 
> If there's anyone like me, I'd appreciate it if you could use it freely.
> 
> link: [nextjs-astroberry](https://github.com/luasenvy/nextjs-astroberry)

Thank you for your kind words! I'm glad you find the theme helpful.
Both Astro and Next.js are great frameworks, and it's awesome that you could adapt it to your needs.
Feel free to share your work or reach out if you have any questions!

Closing this as it's a thank you note. Thanks again for the feedback! 🙌
